name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Decrypt private file
        run: |
          mkdir -p keys
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ZK_PASSPHRASE}}" \
            --output keys/ownership_final.zkey keys/ownership_final.zkey.gpg

      - name: Build Docker image
        run: |
          docker build -t zknft:latest .

      - name: Run Docker Compose
        run: |
          docker compose up --build -d
          sleep 20

      - name: Show Docker logs
        run: |
          docker logs $(docker ps -q --filter "ancestor=zknft:latest")

      - name: Stop Docker Compose
        run: |
          docker compose down

      - name: Cleanups
        run: |
          docker system prune -f
          docker volume prune -f
          docker network prune -f
          docker rmi -f zknft:latest
